# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

before_script:
  - echo "Starting Runner"

after_script:
  - echo "Finished"

build_with_linux:
  stage: build
  tags:
    - linux
  script:
    - echo "Starting Build"
    - mkdir build && cd build
    - ~/Qt/5.12.3/gcc_64/bin/qmake ../qtquick3d.pro
    - make
    - make sub-tests
    - cd tests && make check
  # artifacts:
  #   name: "$CI_JOB_NAME"
  #   paths:
  #   - build/
  #   expire_in: 1 week

# test_with_linux:
#   stage: test
#   tags:
#     - linux
#   script:
#     - cd tests
#     - make check
#   dependencies:
#     - build_with_linux

build_with_windows:
  stage: build
  tags:
    - windows
  script:
    - echo "Starting Build"
    - "call \"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat\""
    - mkdir build
    - cd build
    - "\"C:\\Qt\\5.12.3\\msvc2017_64\\bin\\qmake.exe\" ..\\qtquick3d.pro"
    - "\"C:\\JOM\\JOM.exe\" /J 9"
    - "\"C:\\JOM\\JOM.exe\" sub-tests /J 9"
    - cd tests
    - "\"C:\\JOM\\JOM.exe\" check"
  # artifacts:
  #   name: "%CI_JOB_NAME"
  #   paths:
  #   - build\
  #   expire_in: 1 week

# test_with_windows:
#   stage: test
#   tags:
#     - windows
#   script:
#     - cd "tests"
#     - "\"C:\\JOM\\JOM.exe\" check"
#   dependencies:
#     - build_with_windows